### ISSUE TITLE
BufferError: scalar buffer is readonly

### ISSUE THREAD

**Issue by Laurenz0908** [quadprog/quadprog#16]
Hi,

when I try to run it with quadprog as solver I get the following error:

```
> qps.solve_qp(P=M, q=np.array(means), A=A, b=np.array(1.))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/laurenz/PycharmProjects/GC_aware/venv/lib/python3.8/site-packages/qpsolvers/__init__.py", line 262, in solve_qp
    return quadprog_solve_qp(*args, **kwargs)
  File "/home/laurenz/PycharmProjects/GC_aware/venv/lib/python3.8/site-packages/qpsolvers/quadprog_.py", line 88, in quadprog_solve_qp
    return solve_qp(qp_G, qp_a, qp_C, qp_b, meq)[0]
  File "quadprog/quadprog.pyx", line 12, in quadprog.solve_qp
  File "stringsource", line 672, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 360, in View.MemoryView.memoryview.__cinit__
BufferError: scalar buffer is readonly
```
numpy version is 1.20.1

Would be great if anyone can help.

Thank you!

**Comment by Laurenz0908** [comment]
Sorry nevermind, realized my input was wrong ( works with b = np.array([1.]) )
